// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale ) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> ar = {
  "hello": "مرحبا",
  "Add": "إضافة",
  "Task": "المهمة",
  "LightBlue": "ازرق فاتح & بنفسجي",
  "red": "احمر & زيتي",
  "start": "بدأ",
  "goalDone": "تم إضافة الهدف ",
  "goal_login": "قم بتسجيل الدخول ثم اضف اهدافك ",
  "donthaveAcc": "ليس لدي حساب",
  "email": "البريد الالكتروني",
  "pass": "كلمة المرور",
  "SignUp": "انشاء حساب",
  "taskadded": "تم إضافة المهمة بنجاح",
  "Details": "التفاصيل",
  "ChangeColor": "تغير لون الخلفية",
  "login": "تسجيل دخول",
  "register": "انشاء حساب",
  "settings": "الإعدادات الاساسية",
  "log": "تم تسجيل حسابك",
  "signIn": "تسجيل الدخول",
  "signOut": "تسجيل الخروج",
  "errorMsg": "ادخلت بيانات بشكل خاطئ",
  "wallpaper": "خلفيات",
  "name": "الاسم",
  "whiteTheme": "خلفية الاساسية ",
  "yellowTheme": "الاصفر & الزهري ",
  "RBCs": "فريق الكريات الحمراء",
  "PLEASEENTERTitle": "ادخل العنوان ",
  "title": "ادخل العنوان",
  "time": "التوقيت",
  "time2": "التوقيت و تفاصيل أخرى ",
  "entertime": "ادخل الوقت ",
  "date": "التاريخ",
  "enterDate": "ادخل التاريخ",
  "tasks": "قائمة المهام ",
  "tasks2": "الخطط",
  "tasks3": "المهام",
  "done": "مهام تم تنفيذها",
  "archived": "الارشيف",
  "changeLang": "تغير اللغة",
  "notask": "لا توجد مهام جديدة .. قم بإضافة مهمة جديدة",
  "sixtask": "مهام 6 ساعات",
  "twelvetask": "مهام 12 ساعة",
  "dailytask": "اهداف يومي",
  "weektask": "اهداف أسبوعي",
  "monthtask": "اهداف شهري",
  "yeartask": "اهداف سنوي",
  "dailytask2": "مهام يومية",
  "weektask2": "مهام أسبوعية",
  "monthtask2": "مهام شهرية",
  "yeartask2": "مهام سنوية",
  "dailytask3": "الاهداف اليوم",
  "weektask3": " الاهداف الاسبوع",
  "monthtask3": "الاهداف  الشهر",
  "yeartask3": "الاهداف السنة ",
  "rateApp": "قيم التطبيق",
  "edit": "تعديل",
  "cancel": "إلغاء",
  "ptitle": "تطبيق المهام",
  "pdes": "اهلا بك يمكنك الان إضافة العديد من المهام الجديدة ",
  "ok": "حسنا ",
  "monthGoal": "هدف شهري",
  "weekGoal": "هدف أسبوعي",
  "notes": "ملاحظات هامة ",
  "notes2": "ملاحظات ",
  "dayGoal": "هدف يومي",
  "yearGoal": "هدف سنوي",
  "Goals": "الاهداف",
  "enterdes": "ادخل ملخص المهمة",
  "timeend": "توقيت نهاية المهمة",
  "dateend": "تاريخ انتهاء المهمة",
  "des": "تفاصيل عن المهمة",
  "hours": "ساعات",
  "min": "دقائق",
  "sec": "ثواني",
  "today": "اليوم",
  "late": "متاخرة",
  "tomorrow": "غداً",
  "later": "لاحقاً",
  "TaskDone": "تم إضافة المهمة",
  "TXT": "ضع مهامك المتنوعة هنا وابدا في انجازها اليوم",
  "Tasks2": "المهام الفرعية"
};
static const Map<String,dynamic> en = {
  "hello": "hello222",
  "RBCs": "red",
  "PLEASEENTERTitle": "PLEASE ENTER Title",
  "title": "Title",
  "des": "description",
  "enterdes": "Enter Summary",
  "time": "Time",
  "entertime": "Enter the time ",
  "date": "Date",
  "monthGoal": "Month Goal",
  "weekGoal": "Week Goal ",
  "dayGoal": "Day Goal",
  "yearGoal": "Year Goal",
  "Goals": "Goals",
  "notes": " important notes ",
  "notes2": " notes ",
  "rateApp": "Rate App ",
  "sixtask": "6 Hours tasks",
  "twelvetask": "12 Hours tasks",
  "dailytask": "Daily Goals",
  "weektask": "Weekly Goals",
  "monthtask": "Monthly Goals",
  "tasks3": "Tasks",
  "yeartask": "Yearly Goals",
  "dailytask2": "Daily task",
  "weektask2": "Weekly task",
  "monthtask2": "Monthly task",
  "yeartask2": "Yearly task",
  "dailytask3": "Daily Goals",
  "weektask3": "Weekly Goals",
  "monthtask3": "Monthly Goals",
  "yeartask3": "Yearly Goals",
  "edit": "edit",
  "cancel": "cancel",
  "Tasks2": "subtasks",
  "enterDate": "Enter Date",
  "tasks": " Tasks List",
  "done": "Done Tasks",
  "archived": "Archived",
  "notask": "No New Tasks yet ,add some tasks",
  "changeLang": "Language",
  "ptitle": "Todo List",
  "pdes": "Welcome to our app , enjoy adding new tasks",
  "ok": "ok",
  "Add": "Add",
  "Task": " Task ",
  "Details": "Details",
  "time2": "Time and Others",
  "ChangeColor": "Change background color",
  "timeend": "Time to End the task",
  "dateend": "Date to End the task",
  "tasks2": "Plans",
  "hours": "Hours",
  "min": "Minutes",
  "wallpaper": "background",
  "sec": "Seconds",
  "login": "Login",
  "whiteTheme": "Default Theme",
  "TaskDone": "Task Added Successfully ",
  "TXT": "Add New Tasks Now ",
  "yellowandpinkThme": "Yellow & Pink",
  "register": "Register",
  "settings": "Settings",
  "errorMsg": "Wrong Information",
  "name": "Name",
  "LightBlue": "Light Blue & Pink",
  "red": "Red & Dark Green",
  "donthaveAcc": "Don't have account",
  "email": "Email",
  "pass": "Password",
  "SignUp": "Sign up",
  "start": "Start",
  "goal_login": "Login Then Add Goals",
  "goalDone": " Goal Added",
  "log": "You Already Logged In",
  "today": "Today",
  "late": "Late",
  "tomorrow": "Tomorrow",
  "later": "Later",
  "signIn": "Sign in",
  "signOut": "Sign out"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": ar, "en": en};
}
