// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>> load(String fullPath, Locale locale ) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> ar = {
  "hello": "مرحبا",
  "Add": "إضافة",
  "Task": "المهمة",
  "LightBlue": "ازرق فاتح & بنفسجي",
  "red": "احمر & زيتي",
  "start": "بدء",
  "goalDone": "تم إضافة الهدف ",
  "goal_login": "قم بتسجيل الدخول لكي يمكنك اضافة الأهداف ",
  "donthaveAcc": "ليس لدي حساب",
  "email": "البريد الألكتروني",
  "pass": "كلمة المرور",
  "SignUp": "انشاء حساب",
  "taskadded": "تم إضافة المهمة بنجاح",
  "Details": "التفاصيل",
  "ChangeColor": "تغير لون الخلفية",
  "login": "تسجيل دخول",
  "register": "انشاء حساب",
  "settings": "الإعدادات الأساسية",
  "log": "تم تسجيل حسابك",
  "signIn": "تسجيل الدخول",
  "signOut": "تسجيل الخروج",
  "errorMsg": "ادخلت بيانات بشكل خاطئ",
  "wallpaper": "خلفيات",
  "name": "الأسم",
  "whiteTheme": "خلفية الأساسية ",
  "yellowTheme": "الأصفر & الزهري ",
    "yellowandpinkThme": "الأصفر & الزهري",
  "RBCs": "فريق الكريات الحمراء",
  "PLEASEENTERTitle": "ادخل العنوان ",
  "title": "ادخل العنوان",
  "time": "التوقيت",
  "time2": "التوقيت و تفاصيل أخرى ",
  "entertime": "ادخل الوقت ",
  "date": "التاريخ",
  "enterDate": "ادخل التاريخ",
  "tasks": "قائمة المهام ",
  "tasks2": "الخطط",
  "tasks3": "المهام",
  "done": "مهام تم تنفيذها",
  "archived": "الأرشيف",
  "changeLang": "تغير اللغة",
  "notask": "لا توجد مهام جديدة .. قم بإضافة مهمة جديدة",
  "sixtask": "مهام 6 ساعات",
  "twelvetask": "مهام 12 ساعة",
  "dailytask": "اهداف يومي",
  "weektask": "اهداف أسبوعي",
  "monthtask": "اهداف شهري",
  "yeartask": "اهداف سنوي",
  "dailytask2": "مهام يومية",
  "soon": "قريبا",
  "weektask2": "مهام أسبوعية",
  "monthtask2": "مهام شهرية",
  "yeartask2": "مهام سنوية",
  "dailytask3": "الأداف اليوم",
  "weektask3": " الأهداف الأسبوع",
  "monthtask3": "الأهداف  الشهر",
  "yeartask3": "الأهداف السنة ",
  "rateApp": "قيم التطبيق",
  "goal": "الهدف",
  "cat": "الفئة ",
  "edit": "تعديل",
  "goalEdit": "تم تعديل الهدف بنجاح",
  "cancel": "إلغاء",
  "delete": "حذف",
  "deleteDone": " تم حذف الهدف",
  "ptitle": "تطبيق المهام",
  "pdes": "اهلا بك يمكنك الأن إضافة العديد من المهام الجديدة ",
  "ok": "حسنا ",
  "monthGoal": "هدف شهري",
  "weekGoal": "هدف أسبوعي",
  "notes": "ملاحظات هامة ",
  "notes2": "ملاحظات ",
  "dayGoal": "هدف يومي",
  "yearGoal": "هدف سنوي",
  "Goals": "الأهداف",
  "enterdes": "ادخل ملخص المهمة",
  "timeend": "توقيت نهاية المهمة",
  "dateend": "تاريخ انتهاء المهمة",
  "des": "تفاصيل عن المهمة",
  "hours": "ساعات",
  "min": "دقائق",
  "sec": "ثواني",
  "today": "اليوم",
  "late": "متاخرة",
  "tomorrow": "غداً",
  "later": "لاحقاً",
  "TaskDone": "تم إضافة المهمة",
  "TXT": "ضع مهامك المتنوعة هنا وابدا في انجازها اليوم",
  "Tasks2": "المهام الفرعية"
};
static const Map<String,dynamic> en = {
  "hello": "hello222",
  "RBCs": "red",
  "PLEASEENTERTitle": "PLEASE ENTER Title",
  "title": "Title",
  "des": "description",
  "enterdes": "Enter Summary",
  "time": "Time",
  "entertime": "Enter the time ",
  "date": "Date",
  "monthGoal": "Month Goal",
  "weekGoal": "Week Goal ",
  "dayGoal": "Day Goal",
  "yearGoal": "Year Goal",
  "Goals": "Goals",
  "notes": " important notes ",
  "notes2": " notes ",
  "rateApp": "Rate App ",
  "goal": "Goal",
  "cat": "Category",
  "sixtask": "6 Hours tasks",
  "twelvetask": "12 Hours tasks",
  "dailytask": "Daily Goals",
  "weektask": "Weekly Goals",
  "monthtask": "Monthly Goals",
  "tasks3": "Tasks",
  "yeartask": "Yearly Goals",
  "dailytask2": "Daily task",
  "weektask2": "Weekly task",
  "monthtask2": "Monthly task",
  "yeartask2": "Yearly task",
  "dailytask3": "Daily Goals",
  "weektask3": "Weekly Goals",
  "monthtask3": "Monthly Goals",
  "yeartask3": "Yearly Goals",
  "edit": "edit",
  "goalEdit": "Goal Edited Successfully",
  "cancel": "cancel",
  "Tasks2": "subtasks",
  "enterDate": "Enter Date",
  "delete": "Delete",
  "deleteDone": "Goal Deleted ",
  "tasks": " Tasks List",
  "done": "Done Tasks",
  "archived": "Archived",
  "notask": "No New Tasks yet ,add some tasks",
  "changeLang": "Language",
  "ptitle": "Todo List",
  "pdes": "Welcome to our app , enjoy adding new tasks",
  "ok": "ok",
  "Add": "Add",
  "Task": " Task ",
  "Details": "Details",
  "time2": "Time and Others",
  "ChangeColor": "Change background color",
  "timeend": "Time to End the task",
  "dateend": "Date to End the task",
  "tasks2": "Plans",
  "hours": "Hours",
  "min": "Minutes",
  "wallpaper": "background",
  "sec": "Seconds",
  "login": "Login",
  "whiteTheme": "Default Theme",
  "TaskDone": "Task Added Successfully ",
  "TXT": "Add New Tasks Now ",
  "yellowandpinkThme": "Yellow & Pink Theme",
  "register": "Register",
  "settings": "Settings",
  "errorMsg": "Wrong Information",
  "name": "Name",
  "soon": "Soon",
  "LightBlue": "Light Blue & Pink Theme",
  "red": "Red & Dark Green Theme",
  "donthaveAcc": "Don't have account",
  "email": "Email",
  "pass": "Password",
  "SignUp": "Sign up",
  "start": "Start",
  "goal_login": "Login Then Add Goals",
  "goalDone": " Goal Added",
  "log": "You Already Logged In",
  "today": "Today",
  "late": "Late",
  "tomorrow": "Tomorrow",
  "later": "Later",
  "signIn": "Sign in",
  "signOut": "Sign out"
};
static const Map<String,dynamic> ko = {
  "hello": "안녕하세요",
  "Add": "추가하다",
  "Task": "일",
  "LightBlue": "라이트 블루 & 퍼플",
  "red": "레드＆올리브",
  "start": "시작",
  "goalDone": "대상이 추가되었습니다",
  "goal_login": "목표를 추가하려면 로그인하세요",
  "donthaveAcc": "계정이 없습니다",
  "email": "이메일",
  "pass": "비밀번호",
  "SignUp": "계정 만들기",
  "soon": "곧",
  "taskadded": "작업이 성공적으로 추가되었습니다.",
  "Details": "세부 사항",
  "ChangeColor": "배경색 변경",
  "login": "로그인",
  "register": "계정 만들기",
  "settings": "기본 설정",
  "log": "귀하의 계정이 등록되었습니다",
  "signIn": "로그인",
  "signOut": "로그아웃",
  "errorMsg": "잘못된 데이터를 입력했습니다",
  "wallpaper": "배경",
  "name": "이름",
  "whiteTheme": "기본 바탕화면 ",
  "yellowTheme": "옐로우 & 핑크",
  "yellowandpinkThme": "옐로우 & 핑크",
  "RBCs": "적혈구 그룹",
  "PLEASEENTERTitle": "주소를 입력하세요",
  "title": "주소를 입력하세요",
  "time": "타이밍",
  "time2": "타이밍 및 기타 세부 사항",
  "entertime": "시간을 입력하세요",
  "date": "역사",
  "enterDate": "날짜를 입력하세요",
  "tasks": "할 일 목록",
  "tasks2": "계획",
  "tasks3": "사명",
  "done": "수행된 작업",
  "archived": "아카이브",
  "changeLang": "언어 변경",
  "notask": "새 작업이 없습니다 .. 새 작업 추가",
  "sixtask": "6시간 과제",
  "twelvetask": "12시간 과제",
  "dailytask": "일일 목표",
  "weektask": "주간 목표",
  "monthtask": "월간 목표",
  "yeartask": "연간 목표",
  "dailytask2": "일일 작업",
  "weektask2": "주간 작업",
  "monthtask2": "월간 과제",
  "yeartask2": "연간 과제",
  "dailytask3": "오늘 목표",
  "weektask3": "금주의 목표",
  "monthtask3": "월 목표",
  "yeartask3": "연도 목표",
  "rateApp": "앱 평가하기",
  "edit": "가감",
  "cancel": "해제",
  "ptitle": "작업 신청",
  "pdes": "환영합니다. 이제 많은 새 작업을 추가할 수 있습니다.",
  "ok": "잘 ",
  "monthGoal": "월 목표 ",
  "weekGoal": "주간 목표",
  "notes": "중요 사항",
  "notes2": "메모",
  "dayGoal": "일일 목표",
  "yearGoal": "연간 목표",
  "Goals": "목표",
  "enterdes": "작업 요약 입력",
  "timeend": "작업 종료 시간",
  "dateend": "작업 종료 날짜",
  "des": "과제에 대한 세부정보",
  "hours": "시간",
  "min": "분",
  "sec": "초",
  "today": "오늘",
  "late": "늦은",
  "tomorrow": "내일",
  "later": "나중에",
  "TaskDone": "작업이 추가되었습니다",
  "TXT": "여기에 다양한 작업을 입력하고 오늘 작업을 시작하세요.",
  "Tasks2": "하위 작업"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": ar, "en": en, "ko": ko};
}
